spring:
  application:
    name: kafka-eyone
  data:
    mongodb:
      uri: mongodb://localhost:27017/kafka_eyone
      database: kafka_eyone
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: okok
  cloud:
    function:
      definition: consumePatient
    stream:
      kafka:
        binder:
          brokers: 35.159.23.192:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            spring.json.add.type.headers: false
            spring.json.trusted.packages: "*"
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            auto.offset.reset: earliest
            isolation.level: read_committed
            enable.auto.commit: false
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
              spring.json.use.type.headers: false
      bindings:
        consumePatient-in-0:
          destination: isi-patient-topic
          contentType: application/json
          group: isi-patient-group
          consumer:
            use-native-decoding: false
elasticsearch:
  index:
    transactions:
      name: patients

server:
  port: 8080
application:
  kafka:
    patient-topic: isi-patient-topic

logging:
  level:
    net.eyone.kafka_eyone.services.process.impl.ProcessElasticImpl: DEBUG
    org.springframework.data.mongodb: DEBUG
    net.eyone.kafka_eyone.services.core.impl.MongoServiceImpl: DEBUG

